version: "2.2"

services:
  client:
    build: .
    networks:
      static_network:
        ipv4_address: 192.168.100.2
  router:
    build: .
    networks:
      static_network:
        ipv4_address: 192.168.100.1
  server:
    build: .
    networks:
      static_network:
        ipv4_address: 192.168.101.2
    privileged: true

networks:
  static_network:
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.0/16

