version: "2.2"

services:
  client:
    build:
      context: .
    environment:
      gateway_subaddress: 192.168.100
    networks:
      client_net:
        ipv4_address: 192.168.100.2
    privileged: true
  router:
    build:
      context: .
    environment:
      gateway_subaddress: 192.168.100
    networks:
      client_net:
        ipv4_address: 192.168.100.1
      server_net:
        ipv4_address: 192.168.101.1
    privileged: true
  server:
    build:
      context: .
    environment:
      gateway_subaddress: 192.168.101
    networks:
      server_net:
        ipv4_address: 192.168.101.2
    privileged: true

networks:
  client_net:
    ipam:
      config:
        - subnet: 192.168.100.0/24
          ip_range: 192.168.100.0/24
          gateway: 192.168.100.123
  server_net:
    ipam:
      config:
        - subnet: 192.168.101.0/24
          ip_range: 192.168.101.0/24
          gateway: 192.168.101.123

